version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    container_name: gql-server
    tty: true
    working_dir: /app
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: ['go', 'run', 'cmd/main.go']
    ports:
      - '8080:8080'

  db:
    image: postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-golang_postgres}
