version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    container_name: golang
    tty: true
    working_dir: /app
    volumes:
      - ./backend:/app

  db:
    image: postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-golang_postgres}
