version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - 15432:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
