# workflowの名前
name: deploy actions

on:
  push:
    branches: feat/github_actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
